site_name: Weerwolven regels
theme: 
  name: windmill
  toc:
    depth: 2

nav:
  - Home: index.md
  - Spelregels: 
      - regels/spelverloop.md
      - regels/rollen.md
      - regels/spelleider.md
  - Changelog: changelog.md

markdown_extensions:
  - pymdownx.extra
