site_name: Weerwolven regels
theme: 
  name: windmill
  toc:
    depth: 3

nav:
  - Home: index.md
  - Spelregels: 
      - regels/spelverloop.md
      - Rollen:
          - regels/rollen.md
          - regels/rollen/goed.md
          - regels/rollen/neutraal.md
          - regels/rollen/slecht.md
          - regels/rollen/speciaal.md

      - regels/dodenrijk.md
      - regels/bondjes.md
      - Zwarte dood & andere gekkigheden: regels/gekkigheden.md
      - regels/spelleider.md
  - to-brainstorm.md
  - Extra:
    - Lijst van contribueerders: extra/contributors.md
    - extra/changelog.md
    - extra/rollenarchief.md

markdown_extensions:
  - pymdownx.extra

extra_css:
  - assets/css/custom.css

extra:
  version: "Versie: 27"
