site_name: Weerwolven regels
theme: 
  name: windmill
  toc:
    depth: 3

nav:
  - Home: index.md
  - Spelregels: 
      - regels/spelverloop.md
      - Rollen:
          - regels/rollen.md
          - regels/rollen/goed.md
          - regels/rollen/neutraal.md
          - regels/rollen/slecht.md
          - regels/rollen/speciaal.md

      - regels/dodenrijk.md
      - regels/bondjes.md
      - Zwarte dood & andere gekkigheden: regels/gekkigheden.md
      - regels/spelleider.md
  - Extra:
    - Lijst van contribueerders: contributors.md
    - changelog.md

markdown_extensions:
  - pymdownx.extra
